//! Closed-set ASCII-coded enums for the ITCH 5.0 wire format.
//!
//! Every variant carries an explicit `#[repr(u8)]` discriminant equal
//! to its on-wire ASCII byte. Encode is `value as u8`; decode is one
//! match per variant returning [`ProtocolError::InvalidEnumCode`] on
//! unknown bytes.
//!
//! See `docs/DOMAIN-MODEL.md` §3 and `docs/PROTOCOL-SPEC.md` §4 for
//! the per-message field tables that consume each enum.

use crate::error::ProtocolError;

/// One-byte ASCII codec contract used by every closed-set enum in
/// this module.
///
/// Implementations are generated by the [`enum_alpha`] macro; the
/// trait exists so generic code can refer to "any ITCH ASCII-coded
/// enum" without listing them individually.
pub trait AlphaCoded: Sized + Copy {
    /// Human-readable name carried in [`ProtocolError::InvalidEnumCode`]
    /// when decoding fails.
    const FIELD: &'static str;

    /// Encode the variant as its on-wire ASCII byte.
    fn to_byte(self) -> u8;

    /// Decode an on-wire ASCII byte to a variant.
    ///
    /// # Errors
    ///
    /// Returns [`ProtocolError::InvalidEnumCode`] when the byte does
    /// not match any variant.
    fn from_byte(b: u8) -> Result<Self, ProtocolError>;
}

/// Declares a closed-set ASCII enum and the matching [`AlphaCoded`]
/// impl in one expansion. Round-trip and unknown-byte tests live in
/// the parent module's `#[cfg(test)] mod tests` block — the macro
/// itself does not emit tests.
///
/// Usage:
/// ```ignore
/// enum_alpha! {
///     /// Doc on the enum itself.
///     Side, "Side" => {
///         Buy  = b'B',
///         Sell = b'S',
///     }
/// }
/// ```
#[macro_export]
macro_rules! enum_alpha {
    (
        $(#[$enum_meta:meta])*
        $name:ident, $field:expr => {
            $(
                $(#[$var_meta:meta])*
                $variant:ident = $byte:expr
            ),+ $(,)?
        }
    ) => {
        $(#[$enum_meta])*
        #[repr(u8)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
        pub enum $name {
            $(
                $(#[$var_meta])*
                $variant = $byte,
            )+
        }

        impl $crate::enums::AlphaCoded for $name {
            const FIELD: &'static str = $field;

            #[inline]
            fn to_byte(self) -> u8 {
                self as u8
            }

            #[inline]
            fn from_byte(b: u8) -> ::core::result::Result<Self, $crate::error::ProtocolError> {
                match b {
                    $(
                        $byte => Ok(Self::$variant),
                    )+
                    _ => Err($crate::error::ProtocolError::InvalidEnumCode {
                        field: $field,
                        code: b,
                    }),
                }
            }
        }
    };
}

// ---------------------------------------------------------------------------
// Section 4.1 — System Event
// ---------------------------------------------------------------------------

enum_alpha! {
    /// `S` System Event lifecycle marker.
    EventCode, "EventCode" => {
        /// `O` — Start of Messages.
        StartOfMessages       = b'O',
        /// `S` — Start of System Hours.
        StartOfSystemHours    = b'S',
        /// `Q` — Start of Market Hours.
        StartOfMarketHours    = b'Q',
        /// `M` — End of Market Hours.
        EndOfMarketHours      = b'M',
        /// `E` — End of System Hours.
        EndOfSystemHours      = b'E',
        /// `C` — End of Messages.
        EndOfMessages         = b'C',
    }
}

// ---------------------------------------------------------------------------
// Section 4.2.1 — Stock Directory
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Listing market category.
    MarketCategory, "MarketCategory" => {
        /// `Q` — NASDAQ Global Select.
        NasdaqGlobalSelect = b'Q',
        /// `G` — NASDAQ Global Market.
        NasdaqGlobalMarket = b'G',
        /// `S` — NASDAQ Capital Market.
        NasdaqCapitalMarket = b'S',
        /// `A` — NYSE MKT (formerly NYSE Amex / AMEX).
        NyseMkt            = b'A',
        /// `N` — NYSE Listed.
        Nyse               = b'N',
        /// `P` — NYSE Arca.
        NyseArca           = b'P',
        /// `Z` — BATS BZX Exchange.
        BatsZ              = b'Z',
        /// `V` — Investors Exchange (IEX).
        Iex                = b'V',
        /// ` ` — Unavailable / not categorized.
        Unavailable        = b' ',
    }
}

enum_alpha! {
    /// Financial-status / listing-rule compliance code.
    FinancialStatus, "FinancialStatus" => {
        /// `D` — Deficient (failing one or more listing rules).
        Deficient            = b'D',
        /// `E` — Delinquent (delinquent in regulatory filings).
        Delinquent           = b'E',
        /// `Q` — Bankrupt.
        Bankrupt             = b'Q',
        /// `S` — Suspended.
        Suspended            = b'S',
        /// `G` — Deficient and Bankrupt.
        DeficientAndBankrupt = b'G',
        /// `H` — Deficient and Delinquent.
        DeficientAndDelinquent = b'H',
        /// `J` — Delinquent and Bankrupt.
        DelinquentAndBankrupt = b'J',
        /// `K` — Deficient, Delinquent, and Bankrupt.
        DeficientDelinquentBankrupt = b'K',
        /// `C` — Creations and / or Redemptions Suspended (ETPs only).
        CreationsRedemptionsSuspended = b'C',
        /// `N` — Normal (no listing-rule deficiency).
        Normal               = b'N',
        /// ` ` — Unavailable.
        Unavailable          = b' ',
    }
}

enum_alpha! {
    /// Distinguishes a live symbol from a NASDAQ test symbol.
    Authenticity, "Authenticity" => {
        /// `P` — Live / Production.
        Live = b'P',
        /// `T` — Test.
        Test = b'T',
    }
}

enum_alpha! {
    /// Generic three-state Yes / No / Unavailable used by several
    /// stock-directory sub-fields.
    YesNo, "YesNo" => {
        /// `Y` — Yes.
        Yes         = b'Y',
        /// `N` — No.
        No          = b'N',
        /// ` ` — Unavailable / not specified.
        Unavailable = b' ',
    }
}

enum_alpha! {
    /// LULD (Limit Up / Limit Down) tier.
    LuldTier, "LuldTier" => {
        /// `1` — Tier 1 NMS Stocks and SPDR Futures.
        Tier1       = b'1',
        /// `2` — Tier 2 NMS Stocks.
        Tier2       = b'2',
        /// ` ` — Unavailable / not assigned.
        Unavailable = b' ',
    }
}

// ---------------------------------------------------------------------------
// Section 4.2.2 — Stock Trading Action
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Per-symbol trading state.
    TradingState, "TradingState" => {
        /// `H` — Halted across all U.S. equity markets.
        Halted        = b'H',
        /// `P` — Paused across all U.S. equity markets (LULD).
        Paused        = b'P',
        /// `Q` — Quotation only on NASDAQ.
        QuotationOnly = b'Q',
        /// `T` — Trading on NASDAQ.
        Trading       = b'T',
    }
}

// ---------------------------------------------------------------------------
// Section 4.2.3 — Reg SHO Restriction
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Reg SHO short-sale price-test action.
    RegShoAction, "RegShoAction" => {
        /// `0` — No price test in effect.
        NoPriceTest          = b'0',
        /// `1` — Price test in effect (intraday drop).
        InEffectIntradayDrop = b'1',
        /// `2` — Price test in effect (remaining of the day +
        /// following day).
        InEffect             = b'2',
    }
}

// ---------------------------------------------------------------------------
// Section 4.2.4 — Market Participant Position
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Market-maker quoting mode.
    MarketMakerMode, "MarketMakerMode" => {
        /// `N` — Normal.
        Normal       = b'N',
        /// `P` — Passive.
        Passive      = b'P',
        /// `S` — Syndicate.
        Syndicate    = b'S',
        /// `R` — Pre-syndicate.
        PreSyndicate = b'R',
        /// `L` — Penalty.
        Penalty      = b'L',
    }
}

enum_alpha! {
    /// Market-participant lifecycle state.
    MarketParticipantState, "MarketParticipantState" => {
        /// `A` — Active.
        Active             = b'A',
        /// `E` — Excused / withdrawn.
        ExcusedOrWithdrawn = b'E',
        /// `W` — Withdrawn.
        Withdrawn          = b'W',
        /// `S` — Suspended.
        Suspended          = b'S',
        /// `D` — Deleted.
        Deleted            = b'D',
    }
}

// ---------------------------------------------------------------------------
// Section 4.2.5.2 — MWCB Status
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Market-Wide Circuit Breaker level breached.
    BreachedLevel, "BreachedLevel" => {
        /// `1` — Level 1 (7%).
        Level1 = b'1',
        /// `2` — Level 2 (13%).
        Level2 = b'2',
        /// `3` — Level 3 (20%).
        Level3 = b'3',
    }
}

// ---------------------------------------------------------------------------
// Section 4.2.6 — IPO Quoting Period Update
// ---------------------------------------------------------------------------

enum_alpha! {
    /// IPO release qualifier.
    IpoReleaseQualifier, "IpoReleaseQualifier" => {
        /// `A` — Anticipated.
        Anticipated = b'A',
        /// `C` — Cancelled.
        Cancelled   = b'C',
    }
}

// ---------------------------------------------------------------------------
// Section 4.3 — Add Order
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Buy / sell side.
    Side, "Side" => {
        /// `B` — Buy.
        Buy  = b'B',
        /// `S` — Sell.
        Sell = b'S',
    }
}

// ---------------------------------------------------------------------------
// Section 4.4.2 — Order Executed With Price
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Whether the execution should appear on the consolidated tape.
    Printable, "Printable" => {
        /// `N` — Non-printable.
        NonPrintable = b'N',
        /// `Y` — Printable.
        Printable    = b'Y',
    }
}

// ---------------------------------------------------------------------------
// Section 4.5.2 / 4.6 — Cross Trade / NOII
// ---------------------------------------------------------------------------

enum_alpha! {
    /// NASDAQ cross type.
    CrossType, "CrossType" => {
        /// `O` — Opening cross.
        Opening  = b'O',
        /// `C` — Closing cross.
        Closing  = b'C',
        /// `H` — Halted / IPO cross.
        Halted   = b'H',
        /// `I` — Intraday cross (extended-trading-close, etc.).
        Intraday = b'I',
    }
}

// ---------------------------------------------------------------------------
// Section 4.6 — NOII
// ---------------------------------------------------------------------------

enum_alpha! {
    /// Direction of the order imbalance reported by NOII.
    ImbalanceDirection, "ImbalanceDirection" => {
        /// `B` — Buy imbalance.
        Buy                = b'B',
        /// `S` — Sell imbalance.
        Sell               = b'S',
        /// `N` — No imbalance.
        NoImbalance        = b'N',
        /// `O` — Insufficient orders to calculate.
        InsufficientToCalc = b'O',
    }
}

enum_alpha! {
    /// NOII price-variation indicator (rounded percentage between
    /// the reference price and the near indicative price).
    PriceVariation, "PriceVariation" => {
        /// `L` — Less than 1%.
        LessThan1Percent = b'L',
        /// `1` — 1% to less than 2%.
        Pct1To2          = b'1',
        /// `2` — 2% to less than 3%.
        Pct2To3          = b'2',
        /// `3` — 3% to less than 4%.
        Pct3To4          = b'3',
        /// `4` — 4% to less than 5%.
        Pct4To5          = b'4',
        /// `5` — 5% to less than 6%.
        Pct5To6          = b'5',
        /// `6` — 6% to less than 7%.
        Pct6To7          = b'6',
        /// `7` — 7% to less than 8%.
        Pct7To8          = b'7',
        /// `8` — 8% to less than 9%.
        Pct8To9          = b'8',
        /// `9` — 9% to less than 10%.
        Pct9To10         = b'9',
        /// `A` — 10% to less than 20%.
        Pct10To20        = b'A',
        /// `B` — 20% to less than 30%.
        Pct20To30        = b'B',
        /// `C` — 30% or greater.
        Pct30OrGreater   = b'C',
        /// ` ` — Cannot be calculated.
        CannotBeCalculated = b' ',
    }
}

// ---------------------------------------------------------------------------
// Section 4.7 — Retail Price Improvement
// ---------------------------------------------------------------------------

enum_alpha! {
    /// RPII interest-side flag.
    RpiInterestFlag, "RpiInterestFlag" => {
        /// `B` — Buy-side RPII interest.
        BuySide  = b'B',
        /// `S` — Sell-side RPII interest.
        SellSide = b'S',
        /// `A` — Both sides have RPII interest.
        BothSides = b'A',
        /// `N` — No RPII interest.
        None     = b'N',
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Run a byte-roundtrip + invalid-byte assertion for every
    /// variant of one enum.
    macro_rules! roundtrip_enum {
        ($enum_ty:ty, [ $($variant:expr),+ $(,)? ], invalid: $bad:expr) => {{
            $(
                let v = $variant;
                let b = <$enum_ty as AlphaCoded>::to_byte(v);
                let back = <$enum_ty as AlphaCoded>::from_byte(b)
                    .expect("known byte must decode");
                assert_eq!(back, v, "round-trip mismatch for {:?}", v);
            )+
            let err = <$enum_ty as AlphaCoded>::from_byte($bad)
                .expect_err("unknown byte must fail");
            match err {
                ProtocolError::InvalidEnumCode { field, code } => {
                    assert_eq!(field, <$enum_ty as AlphaCoded>::FIELD);
                    assert_eq!(code, $bad);
                }
            }
        }};
    }

    #[test]
    fn event_code_round_trip() {
        roundtrip_enum!(
            EventCode,
            [
                EventCode::StartOfMessages,
                EventCode::StartOfSystemHours,
                EventCode::StartOfMarketHours,
                EventCode::EndOfMarketHours,
                EventCode::EndOfSystemHours,
                EventCode::EndOfMessages,
            ],
            invalid: b'Z'
        );
    }

    #[test]
    fn side_round_trip() {
        roundtrip_enum!(
            Side,
            [Side::Buy, Side::Sell],
            invalid: b'X'
        );
    }

    #[test]
    fn market_category_round_trip() {
        roundtrip_enum!(
            MarketCategory,
            [
                MarketCategory::NasdaqGlobalSelect,
                MarketCategory::NasdaqGlobalMarket,
                MarketCategory::NasdaqCapitalMarket,
                MarketCategory::NyseMkt,
                MarketCategory::Nyse,
                MarketCategory::NyseArca,
                MarketCategory::BatsZ,
                MarketCategory::Iex,
                MarketCategory::Unavailable,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn financial_status_round_trip() {
        roundtrip_enum!(
            FinancialStatus,
            [
                FinancialStatus::Deficient,
                FinancialStatus::Delinquent,
                FinancialStatus::Bankrupt,
                FinancialStatus::Suspended,
                FinancialStatus::DeficientAndBankrupt,
                FinancialStatus::DeficientAndDelinquent,
                FinancialStatus::DelinquentAndBankrupt,
                FinancialStatus::DeficientDelinquentBankrupt,
                FinancialStatus::CreationsRedemptionsSuspended,
                FinancialStatus::Normal,
                FinancialStatus::Unavailable,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn authenticity_round_trip() {
        roundtrip_enum!(
            Authenticity,
            [Authenticity::Live, Authenticity::Test],
            invalid: b'X'
        );
    }

    #[test]
    fn yesno_round_trip() {
        roundtrip_enum!(
            YesNo,
            [YesNo::Yes, YesNo::No, YesNo::Unavailable],
            invalid: b'X'
        );
    }

    #[test]
    fn luld_tier_round_trip() {
        roundtrip_enum!(
            LuldTier,
            [LuldTier::Tier1, LuldTier::Tier2, LuldTier::Unavailable],
            invalid: b'9'
        );
    }

    #[test]
    fn trading_state_round_trip() {
        roundtrip_enum!(
            TradingState,
            [
                TradingState::Halted,
                TradingState::Paused,
                TradingState::QuotationOnly,
                TradingState::Trading,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn reg_sho_action_round_trip() {
        roundtrip_enum!(
            RegShoAction,
            [
                RegShoAction::NoPriceTest,
                RegShoAction::InEffectIntradayDrop,
                RegShoAction::InEffect,
            ],
            invalid: b'9'
        );
    }

    #[test]
    fn market_maker_mode_round_trip() {
        roundtrip_enum!(
            MarketMakerMode,
            [
                MarketMakerMode::Normal,
                MarketMakerMode::Passive,
                MarketMakerMode::Syndicate,
                MarketMakerMode::PreSyndicate,
                MarketMakerMode::Penalty,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn market_participant_state_round_trip() {
        roundtrip_enum!(
            MarketParticipantState,
            [
                MarketParticipantState::Active,
                MarketParticipantState::ExcusedOrWithdrawn,
                MarketParticipantState::Withdrawn,
                MarketParticipantState::Suspended,
                MarketParticipantState::Deleted,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn breached_level_round_trip() {
        roundtrip_enum!(
            BreachedLevel,
            [BreachedLevel::Level1, BreachedLevel::Level2, BreachedLevel::Level3],
            invalid: b'9'
        );
    }

    #[test]
    fn ipo_release_qualifier_round_trip() {
        roundtrip_enum!(
            IpoReleaseQualifier,
            [IpoReleaseQualifier::Anticipated, IpoReleaseQualifier::Cancelled],
            invalid: b'X'
        );
    }

    #[test]
    fn printable_round_trip() {
        roundtrip_enum!(
            Printable,
            [Printable::NonPrintable, Printable::Printable],
            invalid: b'X'
        );
    }

    #[test]
    fn cross_type_round_trip() {
        roundtrip_enum!(
            CrossType,
            [
                CrossType::Opening,
                CrossType::Closing,
                CrossType::Halted,
                CrossType::Intraday,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn imbalance_direction_round_trip() {
        roundtrip_enum!(
            ImbalanceDirection,
            [
                ImbalanceDirection::Buy,
                ImbalanceDirection::Sell,
                ImbalanceDirection::NoImbalance,
                ImbalanceDirection::InsufficientToCalc,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn price_variation_round_trip() {
        roundtrip_enum!(
            PriceVariation,
            [
                PriceVariation::LessThan1Percent,
                PriceVariation::Pct1To2,
                PriceVariation::Pct2To3,
                PriceVariation::Pct3To4,
                PriceVariation::Pct4To5,
                PriceVariation::Pct5To6,
                PriceVariation::Pct6To7,
                PriceVariation::Pct7To8,
                PriceVariation::Pct8To9,
                PriceVariation::Pct9To10,
                PriceVariation::Pct10To20,
                PriceVariation::Pct20To30,
                PriceVariation::Pct30OrGreater,
                PriceVariation::CannotBeCalculated,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn rpi_interest_flag_round_trip() {
        roundtrip_enum!(
            RpiInterestFlag,
            [
                RpiInterestFlag::BuySide,
                RpiInterestFlag::SellSide,
                RpiInterestFlag::BothSides,
                RpiInterestFlag::None,
            ],
            invalid: b'X'
        );
    }

    #[test]
    fn invalid_enum_code_carries_field_name() {
        // Smoke: confirm the FIELD constant is what propagates.
        let err = <Side as AlphaCoded>::from_byte(b'Z').expect_err("unknown byte must fail");
        match err {
            ProtocolError::InvalidEnumCode { field, code } => {
                assert_eq!(field, "Side");
                assert_eq!(code, b'Z');
            }
        }
    }

    #[test]
    fn discriminant_equals_ascii_byte() {
        // Sanity: the variant discriminant equals the spec's ASCII
        // byte for every #[repr(u8)] enum we ship.
        assert_eq!(Side::Buy as u8, b'B');
        assert_eq!(Side::Sell as u8, b'S');
        assert_eq!(EventCode::StartOfMessages as u8, b'O');
        assert_eq!(EventCode::EndOfMessages as u8, b'C');
        assert_eq!(CrossType::Opening as u8, b'O');
        assert_eq!(BreachedLevel::Level1 as u8, b'1');
    }
}
